
# Author: NNB <nnbnh@protonmail.com>

"ui.menu" = { fg = "black", bg = "white" }
"ui.menu.selected" = { modifiers = ["reversed"] }

"ui.linenr" = { fg = "gray", bg = "#1E1E1E" }
"ui.linenr.selected" = { fg = "light-yellow", bg = "#1E1E1E", modifiers = ["bold"] }

"ui.popup" = { modifiers = ["reversed"] }
"ui.selection" = { fg = "black", bg = "blue" }
"ui.selection.primary" = { fg = "white", bg = "blue" }
"ui.text.inactive" = { fg = "gray" }
"ui.statusline" = { fg = "black", bg = "white" }
"ui.statusline.inactive" = { fg = "gray", bg = "white" }
"ui.cursor" = { fg = "white", modifiers = ["reversed"] }

"ui.background" = { bg = "#1E1E1E" }
"ui.gutter" = { bg = "#1E1E1E" }
"ui.gutter.selected" = { bg = "#1E1E1E" }

"variable" = "#BDB76B"
"variable.builtin" = "#569CD6"

"constant.numeric" = "yellow"
"constant" = "yellow"
"constant.character.escape" = "cyan"

"attributes" = "yellow"

"comment" = "#6A9955"

"type" = "#FFD700"
"type.enum.variant" = "#4FC1FF"

"ui.cursor.match" = { fg = "yellow", modifiers = ["underlined"] }

"string"  = "#CE9178"

"function" = "#FF8000"
"function.macro" = "#C76FBE"

"constructor" = "#4FC1FF"
"special" = "#FF0000"

"keyword" = "#569CD6"
"keyword.control" = "#D8A0DF"

"namespace" = "#B5CEA8"
"ui.help" = { fg = "white", bg = "black" }

"markup.heading" = "blue"
"markup.list" = "red"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "magenta", modifiers = ["italic"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = "red"
"markup.quote" = "cyan"
"markup.raw" = "green"

"diff.plus" = "green"
"diff.delta" = "yellow"
"diff.minus" = "red"

"diagnostic" = { modifiers = ["underlined"] }
"info" = "blue"
"hint" = "gray"
"debug" = "gray"
"warning" = "yellow"
"error" = "red"

"ui.statusline.normal" = { bg = "green" }
"ui.statusline.insert" = { bg = "red" }
"ui.statusline.select" = { bg = "cyan" }
